apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrapper
  template:
    metadata:
      labels:
        app: scrapper
    spec:
      containers:
        - name: scrapper-container
          image: arthpatel11/doccie:my-doccie
